### ISSUE TITLE
Lazy load tabs when switching between groups

### ISSUE THREAD

**Issue by Noexpert** [hupf/tabmarks#11] opened 2017-10-07 16:40 UTC
If it is technically possible, this would allow switching more quickly as only the active tab would load.
The Firefox pref is `browser.sessionstore.restore_on_demand`

Thanks

**Comment by hupf** [comment] 2017-10-14 12:09
I'm closing this as a duplicate of #9

**Closed as completed by hupf** 2017-10-14 12:09 UTC
